.TH IBADDR 8 "June 18, 2007" "OpenIB" "OpenIB Diagnostics"

.SH NAME
ibaddr \- query InfiniBand address(es)

.SH SYNOPSIS
.B ibaddr
[\-d(ebug)] [\-D(irect)] [\-G(uid)] [\-l(id_show)] [\-g(id_show)] [\-C ca_name] 
[\-P ca_port] [\-t(imeout) timeout_ms] [\-V(ersion)] [\-h(elp)]
[<lid | dr_path | guid>]

.SH DESCRIPTION
.PP
Display the lid (and range) as well as the GID address of the
port specified (by DR path, lid, or GUID) or the local port by default.
.PP
Note: this utility can be used as simple address resolver.

.SH OPTIONS

.PP
See infiniband-diags(8) for common options.

.PP
.TP
\fB\-G\fR, \fB\-\-Guid\fR
show lid range and gid for GUID address
.TP
\fB\-l\fR, \fB\-\-lid_show\fR
show lid range only
.TP
\fB\-L\fR, \fB\-\-Lid_show\fR
show lid range (in decimal) only
.TP
\fB\-g\fR, \fB\-\-gid_show\fR
show gid address only


.SH EXAMPLES

.PP
ibaddr                  # local port\'s address
.PP
ibaddr 32               # show lid range and gid of lid 32
.PP
ibaddr -G 0x8f1040023   # same but using guid address
.PP
ibaddr -l 32            # show lid range only
.PP
ibaddr -L 32            # show decimal lid range only
.PP
ibaddr -g 32            # show gid address only

.SH SEE ALSO
.BR ibroute (8),
.BR ibtracert (8)

.SH AUTHOR
.TP
Hal Rosenstock
.RI < halr@voltaire.com >
