.TH IBCCQUERY 8 "Aug 10, 2011" "OpenIB" "OpenIB Diagnostics"

.SH NAME
ibccquery \- query congestion control settings/info

.SH SYNOPSIS
.B ibccquery
[\-d(ebug)] [\-G(uid)] [\-C ca_name] [\-P ca_port] [\-t(imeout) timeout_ms]
[\-V(ersion)] [\-h(elp)] [\-c cckey] <op> <lid|guid> [port]

.SH DESCRIPTION
.PP
.Bibccquery support the querying of settings and other information related
to congestion control.

.SH OPTIONS

.PP
See infiniband-diags(8) for common options.

.PP
.TP
Current supported operations and their parameters:
  CongestionInfo (CI) <addr>
  CongestionKeyInfo (CK) <addr>
  CongestionLog (CL) <addr>
  SwitchCongestionSetting (SS) <addr>
  SwitchPortCongestionSetting (SP) <addr> [<portnum>]
  CACongestionSetting (CS) <addr>
  CongestionControlTable (CT) <addr>
  Timestamp (TI) <addr>

.TP
\fB\-c\-fR, \fB\-\-cckey\fR <cckey>
Specify a congestion control (CC) key.  If none is specified, a key of 0 is used.

.SH EXAMPLES

.PP
ibccquery CongestionInfo 3		# Congestion Info by lid
.PP
ibccquery SwitchPortCongestionSetting 3	# Query all Switch Port Congestion Settings
.PP
ibccquery SwitchPortCongestionSetting 3 1 # Query Switch Port Congestion Setting for port 1

.SH AUTHOR
.TP
Albert Chu
.RI < chu11@llnl.gov >
