.TH IBSTAT 8 "July 25, 2006" "OpenIB" "OpenIB Diagnostics"

.SH NAME
ibstat \- query basic status of InfiniBand device(s)

.SH SYNOPSIS
.B ibstat
[\-d(ebug)] [\-l(ist_of_cas)] [\-s(hort)] [\-p(ort_list)]
[\-V(ersion)] [\-h] <ca_name> [portnum]

.SH DESCRIPTION
.PP
ibstat is a binary which displays basic information obtained from the local
IB driver. Output includes LID, SMLID, port state, link width active, and port
physical state.

It is similar to the ibstatus utility but implemented as a binary rather
than a script. It has options to list CAs and/or ports and displays more
information than ibstatus.

.SH OPTIONS

.PP
See infiniband-diags(8) for common options.

.PP
.TP
\fB\-l\fR, \fB\-\-list_of_cas\fR
list all IB devices
.TP
\fB\-s\fR, \fB\-\-short\fR
short output
.TP
\fB\-p\fR, \fB\-\-port_list\fR
show port list
.TP
ca_name
InfiniBand device name
.TP
portnum
port number of InfiniBand device

.SH EXAMPLES

.PP
ibstat            # display status of all ports on all IB devices
.PP
ibstat -l         # list all IB devices
.PP
ibstat -p         # show port guids
.PP
ibstat mthca0 2   # show status of port 2 of 'mthca0'

.SH SEE ALSO
.BR ibstatus (8)

.SH AUTHOR
.TP
Hal Rosenstock
.RI < halr@voltaire.com >
