.TH IBSYSSTAT 8 "August 11, 2006" "OpenIB" "OpenIB Diagnostics"

.SH NAME
ibsysstat \- system status on an InfiniBand address

.SH SYNOPSIS
.B ibsysstat
[\-d(ebug)] [\-e(rr_show)] [\-v(erbose)] [\-G(uid)]
[\-C ca_name] [\-P ca_port] [\-s smlid] [\-t(imeout) timeout_ms]
[\-V(ersion)] [\-o oui] [\-S(erver)] [\-h(elp)] <dest lid | guid> [<op>]

.SH DESCRIPTION
.PP
ibsysstat uses vendor mads to validate connectivity between IB nodes
and obtain other information about the IB node. ibsysstat is run as
client/server. Default is to run as client.

.SH OPTIONS

.PP
See infiniband-diags(8) for common options.

.PP
.TP
Current supported operations:
 ping \- verify connectivity to server (default)
 host \- obtain host information from server
 cpu  \- obtain cpu information from server
.TP
\fB\-o\fR, \fB\-\-oui\fR
use specified OUI number to multiplex vendor mads
.TP
\fB\-S\fR, \fB\-\-Server\fR
start in server mode (do not return)


.SH AUTHOR
.TP
Hal Rosenstock
.RI < halr@voltaire.com >
