.TH SMINFO 8 "July 25, 2006" "OpenIB" "OpenIB Diagnostics"

.SH NAME
sminfo \- query InfiniBand SMInfo attribute

.SH SYNOPSIS
.B sminfo
[\-d(ebug)] [\-e(rr_show)] -s state -p prio -a activity [\-D(irect)]
[\-G(uid)]  [\-C ca_name] [\-P ca_port] [\-t(imeout) timeout_ms]
[\-V(ersion)] [\-h(elp)] sm_lid | sm_dr_path [modifier]

.SH DESCRIPTION
.PP
Optionally set and display the output of a sminfo query in human readable
format. The target SM is the one listed in the local port info, or the SM
specified by the optional SM lid or by the SM direct routed path.
.PP
Note: using sminfo for any purposes other then simple query may be very
dangerous, and may result in a malfunction of the target SM.

.SH OPTIONS

.PP
See infiniband-diags(8) for common options.

.PP
.TP
\fB\-s\fR
set SM state
 0 - not active
 1 - discovering
 2 - standby
 3 - master
.TP
\fB\-p\fR
set priority (0-15)
.TP
\fB\-a\fR
set activity count


.SH EXAMPLES

.PP
sminfo                  # local port\'s sminfo
.PP
sminfo 32               # show sminfo of lid 32
.PP
sminfo  -G 0x8f1040023  # same but using guid address

.SH SEE ALSO
.BR smpdump (8)

.SH AUTHOR
.TP
Hal Rosenstock
.RI < halr@voltaire.com >
