.TH SMPQUERY 8 "March 9, 2011" "OpenIB" "OpenIB Diagnostics"

.SH NAME
smpquery \- query InfiniBand subnet management attributes

.SH SYNOPSIS
.B smpquery
[\-d(ebug)] [\-e(rr_show)] [\-v(erbose)] [\-D(irect)] [\-G(uid)]
[\-x|\-\-extended] [\-C ca_name] [\-P ca_port] [\-t(imeout) timeout_ms]
[\-\-node-name-map node-name-map] [\-V(ersion)] [\-h(elp)]
<op> <dest dr_path|lid|guid> [op params]

.SH DESCRIPTION
.PP
smpquery allows a basic subset of standard SMP queries including the following:
node info, node description, switch info, port info. Fields are displayed in
human readable format.

.SH OPTIONS

.PP
See infiniband-diags(8) for common options.

.PP
.TP
Current supported operations and their parameters:
        nodeinfo <addr>
        nodedesc <addr>
        portinfo <addr> [<portnum>]     # default port is zero
        switchinfo <addr>
        pkeys <addr> [<portnum>]
        sl2vl <addr> [<portnum>]
        vlarb <addr> [<portnum>]
        guids <addr>
        mlnxextportinfo <addr> [<portnum>]  # default port is zero

.TP
\fB\-x\fR, \fB\-\-extended\fR
Set SMSupportsExtendedSpeeds bit 31 in AttributeModifier
(only impacts PortInfo queries).

.TP
\fB\-\-node\-name\-map\fR <node-name-map>
Specify a node name map.  The node name map file maps GUIDs to more
user friendly names.  See
.B ibnetdiscover(8)
for node name map file format.


.SH EXAMPLES

.PP
smpquery portinfo 3 1        # portinfo by lid, with port modifier
.PP
smpquery -G switchinfo 0x2C9000100D051 1        # switchinfo by guid
.PP
smpquery -D nodeinfo 0       # nodeinfo by direct route
.PP
smpquery -c nodeinfo 6 0,12  # nodeinfo by combined route

.SH SEE ALSO
.BR smpdump (8)

.SH AUTHOR
.TP
Hal Rosenstock
.RI < hal@mellanox.com >
